//! Single file analyzer.

use std::collections::HashSet;
use std::fs;
use std::path::Path;
use std::sync::{Arc, Mutex};

use crate::config::Config;
use crate::error::Result;
use crate::language::LanguageRegistry;

use super::complexity::ComplexityAnalyzer;
use super::counter;
use super::stats::{FileStats, LineStats};

/// Maximum bytes to inspect for binary detection.
const BINARY_CHECK_LEN: usize = 10 * 1024;

/// Analyzes individual source files.
pub struct FileAnalyzer {
    registry: Arc<LanguageRegistry>,
    complexity_analyzer: ComplexityAnalyzer,
    min_lines: Option<usize>,
    max_lines: Option<usize>,
    /// Lowercased language names from `-l`/config; `None` = no filtering.
    allowed_languages: Option<HashSet<String>>,
    /// Content hashes of seen files when `--no-duplicates` is on.
    seen_hashes: Option<Mutex<HashSet<u64>>>,
    /// Skip minified/generated files when `--no-min-gen` is on.
    no_min_gen: bool,
    /// Linguist attributes from .gitattributes (overrides + exclusions).
    linguist: Option<Arc<crate::language::LinguistAttributes>>,
    /// Sink for per-file line hashes (ULOC / duplication analysis).
    dup_sink: Option<Arc<super::duplication::DuplicationSink>>,
}

/// Average bytes per line above which a file is considered minified
/// (same threshold as scc's --min-gen detection).
const MINIFIED_AVG_LINE_LEN: usize = 255;

/// First-line markers that identify generated files.
const GENERATED_MARKERS: &[&[u8]] = &[
    b"Code generated by",
    b"DO NOT EDIT",
    b"@generated",
    b"Autogenerated",
    b"automatically generated",
];

/// Heuristic minified/generated detection on raw bytes.
fn is_minified_or_generated(content: &[u8]) -> bool {
    if content.is_empty() {
        return false;
    }
    // Generated marker in the first line
    let first_line_end = content
        .iter()
        .position(|&b| b == b'\n')
        .unwrap_or(content.len());
    let first_line = &content[..first_line_end];
    if GENERATED_MARKERS.iter().any(|marker| {
        first_line
            .windows(marker.len())
            .any(|w| w.eq_ignore_ascii_case(marker))
    }) {
        return true;
    }
    // Minified: very long average line length
    let lines = content.iter().filter(|&&b| b == b'\n').count().max(1);
    content.len() / lines > MINIFIED_AVG_LINE_LEN
}

impl FileAnalyzer {
    /// Create a new file analyzer.
    pub fn new(registry: Arc<LanguageRegistry>, config: &Config) -> Self {
        let allowed_languages = if config.filter.languages.is_empty() {
            None
        } else {
            Some(
                config
                    .filter
                    .languages
                    .iter()
                    .map(|l| l.to_lowercase())
                    .collect(),
            )
        };
        Self {
            registry,
            complexity_analyzer: ComplexityAnalyzer::new(),
            min_lines: config.filter.min_lines,
            max_lines: config.filter.max_lines,
            allowed_languages,
            seen_hashes: config
                .filter
                .no_duplicates
                .then(|| Mutex::new(HashSet::new())),
            no_min_gen: config.filter.no_min_gen,
            linguist: None,
            dup_sink: None,
        }
    }

    /// Attach linguist attributes (.gitattributes) for language overrides
    /// and vendored/generated exclusion.
    pub fn with_linguist(mut self, linguist: Arc<crate::language::LinguistAttributes>) -> Self {
        self.linguist = Some(linguist);
        self
    }

    /// Attach a duplication sink; every analyzed file reports its line
    /// hashes there for ULOC / duplication computation.
    pub fn with_duplication_sink(mut self, sink: Arc<super::duplication::DuplicationSink>) -> Self {
        self.dup_sink = Some(sink);
        self
    }

    /// Analyze a single file.
    ///
    /// Returns `None` if the file's language is not recognized or the file is binary.
    pub fn analyze(&self, path: &Path) -> Result<Option<FileStats>> {
        let content = match fs::read(path) {
            Ok(bytes) => bytes,
            Err(e) => {
                return Err(crate::error::Error::FileRead {
                    path: path.to_path_buf(),
                    source: e,
                })
            }
        };

        self.analyze_from_bytes(path, &content)
    }

    /// Analyze a file from pre-read bytes (for buffer reuse).
    ///
    /// Returns `None` if the file's language is not recognized or the file is binary.
    pub fn analyze_from_bytes(&self, path: &Path, content: &[u8]) -> Result<Option<FileStats>> {
        // Linguist-vendored/-generated files don't count, matching GitHub.
        if let Some(linguist) = &self.linguist {
            if linguist.is_excluded(path) {
                return Ok(None);
            }
        }

        // Detect language: linguist-language override first, then
        // extension/filename, then shebang fallback.
        let linguist_lang = self
            .linguist
            .as_ref()
            .and_then(|l| l.language_override(path))
            .and_then(|name| self.registry.get(name));
        let language =
            match linguist_lang.or_else(|| self.registry.detect_with_content(path, content)) {
                Some(lang) => lang,
                None => return Ok(None),
            };

        // Apply the language filter (-l / config `lang`), case-insensitively
        if let Some(ref allowed) = self.allowed_languages {
            if !allowed.contains(&language.name.to_lowercase()) {
                return Ok(None);
            }
        }

        // Detect binary files: check first 10KB for null bytes
        let check_len = content.len().min(BINARY_CHECK_LEN);
        if content[..check_len].contains(&0) {
            return Ok(None);
        }

        // Strip a UTF-8 BOM so it isn't counted as line content
        // (otherwise a leading comment/blank line is misclassified as code)
        let content = content
            .strip_prefix(b"\xEF\xBB\xBF".as_slice())
            .unwrap_or(content);

        // Minified/generated file detection (--no-min-gen)
        if self.no_min_gen && is_minified_or_generated(content) {
            return Ok(None);
        }

        // Duplicate-content detection (--no-duplicates): first seen wins
        if let Some(ref seen) = self.seen_hashes {
            use std::hash::{Hash, Hasher};
            let mut hasher = std::collections::hash_map::DefaultHasher::new();
            content.hash(&mut hasher);
            if !seen.lock().unwrap().insert(hasher.finish()) {
                return Ok(None);
            }
        }

        // Count lines using byte-level state machine
        let (trie, mask) = language.tokens();
        let lines: LineStats = counter::count_stats(content, trie, *mask);

        // Apply line filters
        if let Some(min) = self.min_lines {
            if lines.total < min {
                return Ok(None);
            }
        }
        if let Some(max) = self.max_lines {
            if lines.total > max {
                return Ok(None);
            }
        }

        // File size from content length
        let size = content.len() as u64;

        // Analyze complexity (needs string representation)
        let text = String::from_utf8_lossy(content);
        let complexity = self.complexity_analyzer.analyze(&text, &language);

        // Contribute line hashes for the post-walk duplication pass.
        if let Some(sink) = &self.dup_sink {
            let mut hashes = super::duplication::line_hashes(content);
            // Documents and data formats (languages with no complexity
            // signals) repeat lines by the format's nature, not by
            // copy-paste; they count toward ULOC but never toward the
            // duplication metric — same policy that keeps them out of
            // complexity scoring.
            let patterns = language.complexity_patterns();
            if patterns.function_re.is_none() && patterns.keywords_re.is_none() {
                for hash in &mut hashes {
                    hash.1 = false;
                }
            }
            sink.record(path.to_path_buf(), hashes);
        }

        Ok(Some(FileStats {
            path: path.to_path_buf(),
            language: language.name.clone(),
            lines,
            size,
            duplicate_lines: 0,
            complexity,
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    fn make_rust_registry() -> Arc<LanguageRegistry> {
        let mut registry = LanguageRegistry::empty();
        registry
            .load_toml(
                r#"
                [rust]
                name = "Rust"
                extensions = [".rs"]
                line_comments = ["//"]
                block_comments = [["/*", "*/"]]
                nested_comments = true
            "#,
            )
            .unwrap();
        Arc::new(registry)
    }

    fn make_multi_registry() -> Arc<LanguageRegistry> {
        let mut registry = LanguageRegistry::empty();
        registry
            .load_toml(
                r##"
                [rust]
                name = "Rust"
                extensions = [".rs"]
                line_comments = ["//"]

                [python]
                name = "Python"
                extensions = [".py"]
                line_comments = ["#"]
            "##,
            )
            .unwrap();
        Arc::new(registry)
    }

    #[test]
    fn test_language_filter_only_keeps_selected_languages() {
        let mut config = Config::default();
        config.filter.languages = vec!["rust".to_string()]; // lowercase on purpose

        let analyzer = FileAnalyzer::new(make_multi_registry(), &config);

        let kept = analyzer
            .analyze_from_bytes(Path::new("a.rs"), b"fn main() {}\n")
            .unwrap();
        assert!(kept.is_some(), "-l rust must keep Rust files");

        let filtered = analyzer
            .analyze_from_bytes(Path::new("b.py"), b"print(1)\n")
            .unwrap();
        assert!(filtered.is_none(), "-l rust must drop Python files");
    }

    #[test]
    fn test_no_min_gen_skips_minified_and_generated() {
        let mut config = Config::default();
        config.filter.no_min_gen = true;
        let analyzer = FileAnalyzer::new(make_rust_registry(), &config);

        // Generated marker in the first line
        let generated = b"// Code generated by protoc. DO NOT EDIT.\nfn a() {}\n";
        assert!(analyzer
            .analyze_from_bytes(Path::new("gen.rs"), generated)
            .unwrap()
            .is_none());

        // Minified: one very long line
        let mut minified = b"fn main() { ".to_vec();
        minified.extend(std::iter::repeat_n(b'x', 600));
        minified.extend(b" }\n");
        assert!(analyzer
            .analyze_from_bytes(Path::new("min.rs"), &minified)
            .unwrap()
            .is_none());

        // Normal code passes
        assert!(analyzer
            .analyze_from_bytes(Path::new("ok.rs"), b"fn main() {}\n")
            .unwrap()
            .is_some());

        // Detection off by default
        let plain = FileAnalyzer::new(make_rust_registry(), &Config::default());
        assert!(plain
            .analyze_from_bytes(Path::new("gen.rs"), generated)
            .unwrap()
            .is_some());
    }

    #[test]
    fn test_no_duplicates_skips_identical_content() {
        let mut config = Config::default();
        config.filter.no_duplicates = true;
        let analyzer = FileAnalyzer::new(make_rust_registry(), &config);

        let content = b"fn main() {}\n";
        assert!(analyzer
            .analyze_from_bytes(Path::new("a.rs"), content)
            .unwrap()
            .is_some());
        assert!(
            analyzer
                .analyze_from_bytes(Path::new("copy_of_a.rs"), content)
                .unwrap()
                .is_none(),
            "identical content must be skipped with --no-duplicates"
        );
        // Different content still counts
        assert!(analyzer
            .analyze_from_bytes(Path::new("b.rs"), b"fn other() {}\n")
            .unwrap()
            .is_some());
    }

    #[test]
    fn test_utf8_bom_stripped_before_counting() {
        let registry = make_rust_registry();
        let analyzer = FileAnalyzer::new(registry, &Config::default());

        let content = b"\xEF\xBB\xBF// comment\nfn main() {}\n";
        let result = analyzer
            .analyze_from_bytes(Path::new("bom.rs"), content)
            .unwrap()
            .unwrap();

        assert_eq!(result.lines.total, 2);
        assert_eq!(
            result.lines.comment, 1,
            "BOM must not turn a comment line into code"
        );
        assert_eq!(result.lines.code, 1);
    }

    #[test]
    fn test_empty_language_filter_keeps_everything() {
        let analyzer = FileAnalyzer::new(make_multi_registry(), &Config::default());
        assert!(analyzer
            .analyze_from_bytes(Path::new("a.rs"), b"fn main() {}\n")
            .unwrap()
            .is_some());
        assert!(analyzer
            .analyze_from_bytes(Path::new("b.py"), b"print(1)\n")
            .unwrap()
            .is_some());
    }

    #[test]
    fn test_analyze_from_bytes_basic_rust() {
        let registry = make_rust_registry();
        let analyzer = FileAnalyzer::new(registry, &Config::default());

        let content = b"fn main() {\n    println!(\"hello\");\n}\n";
        let path = Path::new("test.rs");
        let result = analyzer.analyze_from_bytes(path, content).unwrap().unwrap();

        assert_eq!(result.lines.total, 3);
        assert_eq!(result.lines.code, 3);
        assert_eq!(result.lines.blank, 0);
        assert_eq!(result.lines.comment, 0);
        assert_eq!(result.language, "Rust");
        assert_eq!(result.size, content.len() as u64);
    }

    #[test]
    fn test_analyze_from_bytes_with_comments() {
        let registry = make_rust_registry();
        let analyzer = FileAnalyzer::new(registry, &Config::default());

        let content = b"// This is a comment\nfn main() {\n    println!(\"hello\");\n}\n";
        let path = Path::new("test.rs");
        let result = analyzer.analyze_from_bytes(path, content).unwrap().unwrap();

        assert_eq!(result.lines.total, 4);
        assert_eq!(result.lines.code, 3);
        assert_eq!(result.lines.comment, 1);
    }

    #[test]
    fn test_analyze_from_bytes_multiline_block_comment() {
        let registry = make_rust_registry();
        let analyzer = FileAnalyzer::new(registry, &Config::default());

        let content = b"/*\n * Multi-line\n * comment\n */\nfn main() {}\n";
        let path = Path::new("test.rs");
        let result = analyzer.analyze_from_bytes(path, content).unwrap().unwrap();

        assert_eq!(result.lines.total, 5);
        assert_eq!(result.lines.code, 1);
        assert_eq!(result.lines.comment, 4);
    }

    #[test]
    fn test_analyze_from_bytes_returns_none_for_unknown_language() {
        let registry = make_rust_registry();
        let analyzer = FileAnalyzer::new(registry, &Config::default());

        let content = b"some content";
        let path = Path::new("test.xyz");
        let result = analyzer.analyze_from_bytes(path, content).unwrap();

        assert!(result.is_none());
    }

    #[test]
    fn test_analyze_from_bytes_detects_binary() {
        let registry = make_rust_registry();
        let analyzer = FileAnalyzer::new(registry, &Config::default());

        let mut content = b"fn main() {}\n".to_vec();
        content.push(0); // null byte makes it binary
        let path = Path::new("test.rs");
        let result = analyzer.analyze_from_bytes(path, &content).unwrap();

        assert!(result.is_none());
    }

    #[test]
    fn test_analyze_from_bytes_complexity() {
        let mut registry = LanguageRegistry::empty();
        registry
            .load_toml(
                r#"
                [rust]
                name = "Rust"
                extensions = [".rs"]
                line_comments = ["//"]
                block_comments = [["/*", "*/"]]
                nested_comments = true
                function_pattern = '(?m)^\s*(pub\s+)?(async\s+)?fn\s+\w+'
                complexity_keywords = ["if", "for"]
            "#,
            )
            .unwrap();
        let registry = Arc::new(registry);
        let analyzer = FileAnalyzer::new(registry, &Config::default());

        let content = b"fn main() {\n    if true {\n        for i in 0..10 {}\n    }\n}\n";
        let path = Path::new("test.rs");
        let result = analyzer.analyze_from_bytes(path, content).unwrap().unwrap();

        assert_eq!(result.complexity.functions, 1);
        assert!(result.complexity.cyclomatic >= 3); // 1 fn + 1 if + 1 for
    }

    #[test]
    fn test_analyze_from_bytes_line_filter_min() {
        let registry = make_rust_registry();
        let mut config = Config::default();
        config.filter.min_lines = Some(10);
        let analyzer = FileAnalyzer::new(registry, &config);

        let content = b"fn main() {}\n";
        let path = Path::new("test.rs");
        let result = analyzer.analyze_from_bytes(path, content).unwrap();

        assert!(
            result.is_none(),
            "File with 1 line should be filtered by min_lines=10"
        );
    }

    #[test]
    fn test_analyze_from_bytes_line_filter_max() {
        let registry = make_rust_registry();
        let mut config = Config::default();
        config.filter.max_lines = Some(1);
        let analyzer = FileAnalyzer::new(registry, &config);

        let content = b"fn main() {\n    println!(\"hello\");\n}\n";
        let path = Path::new("test.rs");
        let result = analyzer.analyze_from_bytes(path, content).unwrap();

        assert!(
            result.is_none(),
            "File with 3 lines should be filtered by max_lines=1"
        );
    }

    #[test]
    fn test_analyze_reads_file_from_disk() {
        let registry = make_rust_registry();
        let analyzer = FileAnalyzer::new(registry, &Config::default());

        let mut tmp = NamedTempFile::with_suffix(".rs").unwrap();
        writeln!(tmp, "fn main() {{}}").unwrap();

        let result = analyzer.analyze(tmp.path()).unwrap().unwrap();
        assert_eq!(result.lines.total, 1);
        assert_eq!(result.lines.code, 1);
        assert_eq!(result.size, 13); // "fn main() {}\n" is 13 bytes
    }

    #[test]
    fn test_analyze_delegates_to_analyze_from_bytes() {
        let registry = make_rust_registry();
        let analyzer = FileAnalyzer::new(registry, &Config::default());

        let mut tmp = NamedTempFile::with_suffix(".rs").unwrap();
        let content = b"// comment\nfn main() {}\n";
        tmp.write_all(content).unwrap();

        let from_disk = analyzer.analyze(tmp.path()).unwrap().unwrap();
        let from_bytes = analyzer
            .analyze_from_bytes(tmp.path(), content)
            .unwrap()
            .unwrap();

        assert_eq!(from_disk.lines, from_bytes.lines);
        assert_eq!(from_disk.size, from_bytes.size);
        assert_eq!(from_disk.language, from_bytes.language);
    }
}
